apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-secret-provider
  namespace: {{ .Values.namespace }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: {{ .Values.clientID }}
    keyvaultName: {{ .Values.keyVaultName }} 
    objects: |
      array:
        - objectName: "DB_USERNAME"
          objectType: "secret"
        - objectName: "DB_PASSWORD"
          objectType: "secret"
        - objectName: "{{ .Values.DB_HOST_KEY }}"
          objectType: "secret"          
    tenantID: {{ .Values.tenantID }}
  secretObjects:
  - secretName: app-secrets
    type: Opaque
    data:
      - objectName: "DB_USERNAME"
        key: "DB_USERNAME"
      - objectName: "DB_PASSWORD"
        key: "DB_PASSWORD"
      - objectName: "{{ .Values.DB_HOST_KEY }}"
        key: "{{ .Values.DB_HOST_KEY }}"